2013/01/03 21:51:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 21:51:04 [error] [system.db.CDbCommand] CDbCommand::fetch() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii_grouphug.tbl_profile' doesn't exist. The SQL statement executed was: SELECT `Auto_increment`
FROM `information_schema`.`tables`
JOIN `tbl_profile` `p` ON u.id=p.user_id
WHERE table_name=:table_name.
in C:\xampp\htdocs\gh-1228\protected\views\site\index.php (13)
in C:\xampp\htdocs\gh-1228\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\gh-1228\index.php (13)
2013/01/03 21:51:05 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii_grouphug.tbl_profile' doesn't exist. The SQL statement executed was: SELECT `Auto_increment`
FROM `information_schema`.`tables`
JOIN `tbl_profile` `p` ON u.id=p.user_id
WHERE table_name=:table_name' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:528
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbCommand.php(408): CDbCommand->queryInternal('fetch', Array, Array)
#1 C:\xampp\htdocs\gh-1228\protected\views\site\index.php(13): CDbCommand->queryRow()
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(870): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#5 C:\xampp\htdocs\yii\framework\web\CController.php(783): CController->renderPartial('index', NULL, true)
#6 C:\xampp\htdocs\gh-1228\protected\controllers\SiteController.php(32): CController->render('index')
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(283): CController->run('')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/gh-1228/
---
2013/01/03 21:52:22 [error] [exception.CException] exception 'CException' with message 'Object configuration must be an array containing a "class" element.' in C:\xampp\htdocs\yii\framework\YiiBase.php:195
Stack trace:
#0 C:\xampp\htdocs\yii\framework\base\CModule.php(387): YiiBase::createComponent(Array)
#1 C:\xampp\htdocs\yii\framework\base\CModule.php(104): CModule->getComponent('ai')
#2 C:\xampp\htdocs\gh-1228\protected\views\site\index.php(8): CModule->__get('ai')
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#4 C:\xampp\htdocs\yii\framework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#5 C:\xampp\htdocs\yii\framework\web\CController.php(870): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#6 C:\xampp\htdocs\yii\framework\web\CController.php(783): CController->renderPartial('index', NULL, true)
#7 C:\xampp\htdocs\gh-1228\protected\controllers\SiteController.php(32): CController->render('index')
#8 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(283): CController->run('')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/gh-1228/
---
2013/01/03 21:52:40 [error] [exception.CException] exception 'CException' with message 'Object configuration must be an array containing a "class" element.' in C:\xampp\htdocs\yii\framework\YiiBase.php:195
Stack trace:
#0 C:\xampp\htdocs\yii\framework\base\CModule.php(387): YiiBase::createComponent(Array)
#1 C:\xampp\htdocs\yii\framework\base\CModule.php(104): CModule->getComponent('ai')
#2 C:\xampp\htdocs\gh-1228\protected\views\site\index.php(8): CModule->__get('ai')
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#4 C:\xampp\htdocs\yii\framework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#5 C:\xampp\htdocs\yii\framework\web\CController.php(870): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#6 C:\xampp\htdocs\yii\framework\web\CController.php(783): CController->renderPartial('index', NULL, true)
#7 C:\xampp\htdocs\gh-1228\protected\controllers\SiteController.php(32): CController->render('index')
#8 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(283): CController->run('')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/gh-1228/
---
2013/01/03 21:54:24 [error] [php] Array to string conversion (C:\xampp\htdocs\gh-1228\protected\views\site\index.php:13)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(870): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(783): SiteController->renderPartial()
#2 C:\xampp\htdocs\gh-1228\protected\controllers\SiteController.php(32): SiteController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(309): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(287): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(266): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(283): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#10 C:\xampp\htdocs\gh-1228\index.php(13): CWebApplication->run()
REQUEST_URI=/gh-1228/
in C:\xampp\htdocs\gh-1228\protected\views\site\index.php (13)
in C:\xampp\htdocs\gh-1228\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\gh-1228\index.php (13)
2013/01/03 21:57:18 [error] [system.db.CDbCommand] CDbCommand::fetch() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' table_schema='yii_grouphug'' at line 3. The SQL statement executed was: SELECT `Auto_increment`
FROM `tables`
WHERE table_name=:table_name, table_schema=:table_schema.
in C:\xampp\htdocs\gh-1228\protected\views\site\index.php (12)
in C:\xampp\htdocs\gh-1228\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\gh-1228\index.php (13)
2013/01/03 21:57:19 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' table_schema='yii_grouphug'' at line 3. The SQL statement executed was: SELECT `Auto_increment`
FROM `tables`
WHERE table_name=:table_name, table_schema=:table_schema' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:528
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbCommand.php(408): CDbCommand->queryInternal('fetch', Array, Array)
#1 C:\xampp\htdocs\gh-1228\protected\views\site\index.php(12): CDbCommand->queryRow()
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(870): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#5 C:\xampp\htdocs\yii\framework\web\CController.php(783): CController->renderPartial('index', NULL, true)
#6 C:\xampp\htdocs\gh-1228\protected\controllers\SiteController.php(32): CController->render('index')
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(283): CController->run('')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/gh-1228/
---
2013/01/03 21:59:05 [error] [exception.CException] exception 'CException' with message 'CDbCommand and its behaviors do not have a method or closure named "andWhere".' in C:\xampp\htdocs\yii\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\gh-1228\protected\views\site\index.php(12): CComponent->__call('andWhere', Array)
#1 C:\xampp\htdocs\gh-1228\protected\views\site\index.php(12): CDbCommand->andWhere('table_schema=:t...', Array)
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(870): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#5 C:\xampp\htdocs\yii\framework\web\CController.php(783): CController->renderPartial('index', NULL, true)
#6 C:\xampp\htdocs\gh-1228\protected\controllers\SiteController.php(32): CController->render('index')
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(283): CController->run('')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/gh-1228/
---
2013/01/03 22:00:14 [error] [system.db.CDbCommand] CDbCommand::fetch() failed: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens. The SQL statement executed was: SELECT `Auto_increment`
FROM `tables`
WHERE table_schema=:table_schema.
in C:\xampp\htdocs\gh-1228\protected\views\site\index.php (13)
in C:\xampp\htdocs\gh-1228\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\gh-1228\index.php (13)
2013/01/03 22:00:15 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens. The SQL statement executed was: SELECT `Auto_increment`
FROM `tables`
WHERE table_schema=:table_schema' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:528
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbCommand.php(408): CDbCommand->queryInternal('fetch', Array, Array)
#1 C:\xampp\htdocs\gh-1228\protected\views\site\index.php(13): CDbCommand->queryRow()
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(127): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(96): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(870): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#5 C:\xampp\htdocs\yii\framework\web\CController.php(783): CController->renderPartial('index', NULL, true)
#6 C:\xampp\htdocs\gh-1228\protected\controllers\SiteController.php(32): CController->render('index')
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(283): CController->run('')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#14 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/gh-1228/
---
2013/01/03 22:02:28 [error] [php] Undefined index: Auto_increment (C:\xampp\htdocs\gh-1228\protected\views\site\index.php:13)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(870): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(783): SiteController->renderPartial()
#2 C:\xampp\htdocs\gh-1228\protected\controllers\SiteController.php(32): SiteController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): SiteController->actionIndex()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(309): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(287): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(266): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(283): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#10 C:\xampp\htdocs\gh-1228\index.php(13): CWebApplication->run()
REQUEST_URI=/gh-1228/
in C:\xampp\htdocs\gh-1228\protected\views\site\index.php (13)
in C:\xampp\htdocs\gh-1228\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\gh-1228\index.php (13)
2013/01/03 22:05:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:05:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:05:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:08:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:08:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:08:10 [error] [exception.CDbException] exception 'CDbException' with message 'The active record cannot be updated because it is new.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:1115
Stack trace:
#0 C:\xampp\htdocs\gh-1228\protected\models\Confessions.php(146): CActiveRecord->saveAttributes(Array)
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1011): Confessions->beforeSave()
#2 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(796): CActiveRecord->insert(NULL)
#3 C:\xampp\htdocs\gh-1228\protected\controllers\ConfessionsController.php(79): CActiveRecord->save()
#4 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): ConfessionsController->actionCreate()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(1146): CFilter->filter(Object(CFilterChain))
#9 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(59): CController->filterAccessControl(Object(CFilterChain))
#10 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#11 C:\xampp\htdocs\yii\framework\web\CController.php(292): CFilterChain->run()
#12 C:\xampp\htdocs\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(283): CController->run('create')
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('confessions/cre...')
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#16 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/gh-1228/confessions/new
HTTP_REFERER=http://localhost:8080/gh-1228/confessions/new
---
2013/01/03 22:09:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:09:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:09:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:10:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:10:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:10:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:10:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:10:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:13:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:13:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:14:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:14:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:14:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:14:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:14:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:14:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:15:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:15:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:15:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:15:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:16:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:17:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:17:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:17:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:17:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:17:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:17:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:17:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:17:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:22:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:22:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:22:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:22:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:22:20 [error] [php] Undefined variable: hash (C:\xampp\htdocs\gh-1228\protected\models\Confessions.php:155)
Stack trace:
#0 C:\xampp\htdocs\gh-1228\protected\controllers\ConfessionsController.php(79): Confessions->save()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): ConfessionsController->actionCreate()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(309): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): ConfessionsController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(1146): CAccessControlFilter->filter()
#6 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(59): ConfessionsController->filterAccessControl()
#7 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(292): CFilterChain->run()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(266): ConfessionsController->runActionWithFilters()
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(283): ConfessionsController->run()
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController()
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#13 C:\xampp\htdocs\gh-1228\index.php(13): CWebApplication->run()
REQUEST_URI=/gh-1228/confessions/new
in C:\xampp\htdocs\gh-1228\protected\models\Confessions.php (155)
in C:\xampp\htdocs\gh-1228\protected\controllers\ConfessionsController.php (79)
in C:\xampp\htdocs\gh-1228\index.php (13)
2013/01/03 22:22:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:23:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:23:03 [error] [php] Undefined variable: link (C:\xampp\htdocs\gh-1228\protected\models\Confessions.php:155)
Stack trace:
#0 C:\xampp\htdocs\gh-1228\protected\controllers\ConfessionsController.php(79): Confessions->save()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): ConfessionsController->actionCreate()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(309): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): ConfessionsController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(1146): CAccessControlFilter->filter()
#6 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(59): ConfessionsController->filterAccessControl()
#7 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(292): CFilterChain->run()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(266): ConfessionsController->runActionWithFilters()
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(283): ConfessionsController->run()
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController()
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#13 C:\xampp\htdocs\gh-1228\index.php(13): CWebApplication->run()
REQUEST_URI=/gh-1228/confessions/new
in C:\xampp\htdocs\gh-1228\protected\models\Confessions.php (155)
in C:\xampp\htdocs\gh-1228\protected\controllers\ConfessionsController.php (79)
in C:\xampp\htdocs\gh-1228\index.php (13)
2013/01/03 22:23:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:24:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:24:02 [error] [php] Undefined variable: link (C:\xampp\htdocs\gh-1228\protected\models\Confessions.php:160)
Stack trace:
#0 C:\xampp\htdocs\gh-1228\protected\controllers\ConfessionsController.php(79): Confessions->save()
#1 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(50): ConfessionsController->actionCreate()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(309): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(134): ConfessionsController->runAction()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(41): CFilterChain->run()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(1146): CAccessControlFilter->filter()
#6 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(59): ConfessionsController->filterAccessControl()
#7 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(292): CFilterChain->run()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(266): ConfessionsController->runActionWithFilters()
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(283): ConfessionsController->run()
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController()
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#13 C:\xampp\htdocs\gh-1228\index.php(13): CWebApplication->run()
REQUEST_URI=/gh-1228/confessions/new
in C:\xampp\htdocs\gh-1228\protected\models\Confessions.php (160)
in C:\xampp\htdocs\gh-1228\protected\controllers\ConfessionsController.php (79)
in C:\xampp\htdocs\gh-1228\index.php (13)
2013/01/03 22:24:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:24:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:24:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:24:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:24:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:43:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:43:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:43:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:43:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:45:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:45:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:45:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:45:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:52:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:52:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 22:52:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 23:16:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 23:25:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
2013/01/03 23:25:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 C:\xampp\htdocs\gh-1228\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gh-1228/favicon.ico
---
